name: Lint & test & deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Find Node version to install
        run: |
          NODE_VERSION=$(sed 's/^v//' .nvmrc)
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-node-
      - name: Install Node dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: build
